### ISSUE TITLE
Bug: extension broken on preview.duolingo.com

### ISSUE THREAD

**Issue by Atervanda** [blmage/duolingo-solution-viewer#108]
Hi!

The extension has completely stopped working on preview.duolingo.com, the website used for beta testing. Checked in Firefox, Firefox Nightly, and Chrome.

**Comment by blmage** [comment]
Looks like they made some changes to the "result footers", I'll publish a fix today.

Thanks for the report!

**Comment by blmage** [comment]
The fixed version (`3.0.3`) is now available on both stores. Let me know if you find something missing!
