### ISSUE TITLE
Closest solution is not shown anymore in case of a typo in a "Type what you hear" exercise

### ISSUE THREAD

**Issue by dlhgl** [blmage/duolingo-solution-viewer#118]
For example in the following screenshot there is a typo (_singe_ instead of _synge_), but no closest solution is shown:

![2020-09-16_16-27_](https://user-images.githubusercontent.com/53402739/93382320-82e05200-f851-11ea-845f-066e726c2912.png)

This may be caused by Duolingo not showing the translation anymore (maybe it's an A/B test and not everyone is affected).

**Comment by blmage** [comment]
Since the translation shouldn't be necessary to detect the current listening challenge in most cases, I've just released a patch version to make it optional.

Let me know if this fixes your problem (it seems to indeed be an A/B test), and thanks for the report!

**Comment by dlhgl** [comment]
Yes the problem is fixed. Thanks :)
