### ISSUE TITLE
idea: Allow solution window to be relocated on the screen

### ISSUE THREAD

**Issue by bsimon1** [blmage/duolingo-solution-viewer#136]
This is a useful app; I've learned a few things from being able to view all the possible solutions to an exercise.
It would be helpful to be able to move the solution window to the right so I could see my translation.  I sometimes get an exercise marked wrong because I either omitted a preposition or added one that doesn't belong and I can't always remember exactly what I wrote.

**Comment by blmage** [comment]
Thanks for your feedback!

Your answer should be visible above the solution list:

![image](https://user-images.githubusercontent.com/25432517/97431279-558bc700-191a-11eb-805a-4323520f88ff.png)

And the next major version will feature a button to make it stick to the top of the solution window when scrolling down the list.
