### ISSUE TITLE
Idea: What skill a sentence belongs to ? 

### ISSUE THREAD

**Issue by alexseyk** [blmage/duolingo-solution-viewer#140]
I wonder if it is possible to determine (show)  to what skill a sentence belongs to ? It will be useful in general practice and skills test out via "castles" type exercises . When i fail   a particular sentence i would like to know to what skill it belongs to, so i can practice that skill more. 
My post [What skill(s) a sentence belong to?](https://forum.duolingo.com/comment/36478601) did not result in any good suggestions :(

**Comment by blmage** [comment]
This won't be possible in a consistent way, because the corresponding information isn't available by default (we could only store it on regular lessons, and display it on previously encountered sentences).
