### ISSUE TITLE
Feature: Keyboard shortcut for opening discussion page

### ISSUE THREAD

**Issue by stochaztic** [blmage/duolingo-solution-viewer#142]
A keyboard shortcut being added to open the discussion page (in a new tab, just like clicking the vanilla link) would be helpful. I always want to check the discussion page on a new sentence, mousing to the tiny link is annoying, and the keyboard shortcuts like those provided to interact with the solutions are much more convenient and would be a welcome addition.

**Comment by blmage** [comment]
Good idea, thanks!

This is now available in version `4.2.0`, by pressing on <kbd>D</kbd>.

**Comment by alexseyk** [comment]
Can you also add shortcut for Report , say **R** ? Also with solutions open, it would be nice, for shortcuts to work too : i.e. bypassing the need to press Esc first,  so that D = Esc then D & R = Esc then R.   

and/ or add a link to discussions in the solutions window
Thanks

**Comment by alexseyk** [comment]
and maybe enable shortcut **S** from discussion page too ?

**Comment by blmage** [comment]
@alexseyk Everything you mentioned is now available in version `4.4.0`, thanks for the suggestions!
