### ISSUE TITLE
Bug: typing 'f' interrupts writing a comment by focusing on the filter 

### ISSUE THREAD

**Issue by Felicity-R** [blmage/duolingo-solution-viewer#143]
**Steps to reproduce**:
1. Go to the sentence discussion of some sentence with the extension enabled
2. Expand the 'Solutions' section
3. Scroll down and start to create a comment/reply, typing a word containing the letter 'f'

**Expected result**:
You should be able to type your comment, without the filter taking focus away when you're focused on a text box.

**Actual result**:
When you press 'f', it switches your focus to the filter and scrolls you to the top of the page. Now you have to scroll back down to the comment you were writing and click on the text box again to re-focus it in order to continue, which is jarring and is especially troublesome if you were replying to a comment way down the page.

As a workaround you can close the 'Solutions' section which stops the 'f' hotkey from having an effect.

**Comment by blmage** [comment]
Thanks for catching this one!
