### ISSUE TITLE
Bug: Some sentences display wrong language in solutions during lessons only

### ISSUE THREAD

**Issue by stochaztic** [blmage/duolingo-solution-viewer#144]
I have not determined what causes this, but in rare cases, some sentences are displaying the incorrect language solutions when encountered in lessons, but not when clicking the discussion link from that lesson. Example image of the bug below:

![image](https://user-images.githubusercontent.com/8549883/103218075-13fea480-48e8-11eb-8d0a-8cee461db0f4.png)

However, if the Discuss link is clicked, you go to [this page](https://forum.duolingo.com/comment/39310277) which correctly lists the 33 English solutions instead of the two Japanese solutions.

If I figure out anything more about the cause of this bug I will add to this issue.

**Comment by blmage** [comment]
Pretty sure this should be fixed in version `4.4.0` (/ probably related to 9ca6e4ca5ea3312b17acea1d96b85887aa3d0de2).

Feel free to reopen this issue if this happens again!
