### ISSUE TITLE
I don't see the solutions on the forum/discussion pages

### ISSUE THREAD

**Issue by sassfb** [blmage/duolingo-solution-viewer#148]
I recently added the solution-viewer extension to Chrome on my mac (running MacOS Catalina, version 10.15.7). When I am going through the lessons, I do see the solutions after I supply an answer: the SOLUTIONS button appears after the REPORT and DISCUSS buttons at the bottom. And if I bring up the discussion page **at that time** (with the DISCUSS button), I see the SOLUTIONS button to the left of the REPORT button at the top of the page, under the Duolingo sentence and correct answer. But if I bring up a discussion page from the VIEW OR REPLY link in an email (from a discussion I'm following) or a page I find from a search on forum.duolingo.com, I don't see the solutions. There is nothing to the left of the REPORT button.

Another user told me that I should be able to see the solutions on discussion pages as well. Since I answer a lot of user questions, it would be very useful to be able to tell users whether certain words or phrases are included in the accepted solutions. I almost always access the discussion pages via links in emails, not when I am actually going through the lesson myself.

Am I missing something? I am new to this extension, and it could be user error here. Thank you!

**Comment by blmage** [comment]
Solutions should always be available in the forum, no matter where you came from, but only for discussions for which you have already encountered the corresponding exercise while the extension was active.

If this isn't (always) the case, could you point me to some course/skill that I could use to try and reproduce the problem?

**Comment by sassfb** [comment]
Thank you! Since I only recently installed the extension, it wasn't active for the exercises I answer questions for, so I'm sure that that is the reason.

I appreciate your prompt reply!




________________________________
