### ISSUE TITLE
Russian е & ё

### ISSUE THREAD

**Issue by alexseyk** [blmage/duolingo-solution-viewer#152]
In Russian it is OK & acceptable to type **е** instead of **ё**, However the reverse is not true and is an error. Few words aside (небо-нёбо, все-всё, ...) the substitute only affects pronunciation &  writing esthetics, but not the meaning.   Is it possible to stop marking **e** as an error / typo and NOT to suggest the usage of **ё** ? Thanks 
<img width="442" alt="Screen Shot 2021-04-06 at 09 49 48" src="https://user-images.githubusercontent.com/60418150/113652156-745a6a80-96bd-11eb-9b64-90708fd8fd10.png">

**Comment by blmage** [comment]
Thanks for the insight! (I was wondering recently if this kind of exception could exist, this answers my question)

This will be implemented in the next version.
