### ISSUE TITLE
Issue with suggestion drop-down styling in filter

### ISSUE THREAD

**Issue by Felicity-R** [blmage/duolingo-solution-viewer#157]
When typing in the filter, a helpful list of suggestions appears. Right now the styling for that list of suggestions has issues - it apparently has no background, so the text is overlayed with the list of solutions in a way that looks very bad:

![image](https://user-images.githubusercontent.com/62772237/117759194-34b10200-b1d8-11eb-8c8a-2f5ce5b6dbab.png)

Seen in Chrome Version 90.0.4430.93 and Version 90.0.4430.212 (Official Build) (64-bit), on Windows 10.

**Comment by blmage** [comment]
Thanks for reporting this problem! (I really need to find a solution to automatically detect UI changes)
