### ISSUE TITLE
Solution viewer not working with latest Duo update

### ISSUE THREAD

**Issue by wizofaus** [blmage/duolingo-solution-viewer#169]
Maybe premature as they're still obviously working on things (other stuff doesn't work either - forum pages don't load at all etc.) but as a heads up, the Chrome solution viewer (latest version) is not working at all (no solutions are shown).
Haven't tried other browsers.

Update: all Duolingo functionality seems to be restored (maybe was related to AWS outage?), but solutions are still not showing in exercises. They work in forums/discussion pages.

**Comment by blmage** [comment]
Thanks for letting me know!

There have been some changes to the UI that break the detection of exercises, I'll publish a new version to fix this problem first thing tomorrow.
