### ISSUE TITLE
Mousing over "Key" icon enlarges bottom of web page in Firefox

### ISSUE THREAD

**Issue by RufusWoodyIII** [blmage/duolingo-solution-viewer#170]
Hello,
I love this Duolingo browser extension for Firefox. 
<img width="1048" alt="GermanBrowserAdd-InProblem" src="https://user-images.githubusercontent.com/97049904/147964305-2cefcd6e-b8ad-4644-81e7-7513f2f2c36f.png">
However, I'm having an issue with the web page becoming unusable if I accidentally mouse over the "Key" while looking at the results after a response. The "Key" enlarges greatly, forcing the bottom part of the web page to enlarge, and then usually does it again, covering up the problem and/or the answer I am trying to study. I am using the latest release of Firefox (95.0.2 64-bit) on an up-to-date macOS (Big Sur 11.6.2) on a MacBook Pro (Retina display, late 2013). I have attached a file that illustrates the problem. Thank you for any help you may be able to provide. [Sorry, I accidentally attached two copies and don't know how to get rid of the second one!) 
Again, I LOVE this Duolingo browser extension! 
Regards, 
Rufus
:-)>

**Comment by aquafemi** [comment]
I'm experiencing this too

**Comment by RufusWoodyIII** [comment]
I have noticed that, when the screen displays an "old-style" graphic for the solution key, this problem does not occur. See this diagram. I don't know if it is Duolingo or the add-in developer who determines which graphic is used, but whatever is different is "part of the problem". Thanks in advance! 
:-)
<img width="956" alt="OldStyleSolutionKey" src="https://user-images.githubusercontent.com/97049904/148631050-46de9ed9-87e9-42ad-9a66-8a2a085c0359.png">

**Comment by blmage** [comment]
@RufusWoodyIII 

Thanks!

I couldn't reproduce the problem, but similar behavior has been reported from time to time (the current solution does not seem 100% consistent).

Version `4.10.0` features a possible fix, could you give it a try and report whether you still experience problems with the icons?

@aquafemi 

There were probably two instances of the extension running at the same time after that. Let me know if everything is not back to normal though.

**Comment by RufusWoodyIII** [comment]
I don't know exactly what fixed this, but the problem doesn't seem to occur any longer. I am running 4.10.0. 
THANK YOU!! 
Until further news, you may consider this "solved" from my viewpoint! Again, THANK YOU for the timely follow-up!!
:-)>
