### ISSUE TITLE
[cmd]+[f] keyboard shortcut to find-in-page function is broken on forum discussion pages for exercises with multiple solutions

### ISSUE THREAD

**Issue by cueedee** [blmage/duolingo-solution-viewer#172]
When this plugin is active, Chrome's own find-in-page function cannot be accessed via the <kbd>cmd</kbd>+<kbd>f</kbd> keyboard shortcut while on a forum discussion page for an exercise that has multiple solutions. 

---
Example of a discussion page that _does_ exhibit the behavior (exercise with 33+ solutions):

https://forum.duolingo.com/comment/32843215

Ensure that keyboard focus is _not_ on any form input field control, and wait until after the "**solutions (...)**" label has appeared.

---
Example of a discussion page that does _not_ exhibit the behavior (exercise with only 1 solution):

https://forum.duolingo.com/comment/31972783

---

**Plugin:** 4.10.0;  
**System:** macOS 10.15.7 Catalina;  
**Chrome:** Version 98.0.4758.80 (Official Build) (x86_64). (the latest at time of writing);

**Comment by blmage** [comment]
Thank you very much for all these detailed reports!

This should be fixed by e67ac7a41bc19b6802c841705fddd85d0584c3ed - could you let me know if the problem still exists once version `4.11.0` is published?

**Comment by cueedee** [comment]
Sure, I'll keep an eye out for its release.

**Comment by cueedee** [comment]
Speaking of releases, I see you've progressed to version `4.10.2` already; yet the Chrome web store still ships `4.10.0`... any estimate on when it'll be published there?

**Comment by blmage** [comment]
It is available now! (review usually takes up to a day on the Chrome store, but got delayed this time because of requested permissions that were no longer needed)

**Comment by cueedee** [comment]
Got it, and I can confirm that this now works.
