### ISSUE TITLE
UI elements don't match Duolingo's colors

### ISSUE THREAD

**Issue by cueedee** [blmage/duolingo-solution-viewer#177]
Apparently, Duolingo recently changed it's stylesheet just enough to cause some of the plugin's UI elements to no longer mimic Duo's color scheme; examples:

<img width="286" alt="Screen Shot 2022-03-02 at 09 33 39 " src="https://user-images.githubusercontent.com/7399805/156325298-649d8068-1e09-48d2-bbec-c94ed289b1ee.png">

<img width="421" alt="Screen Shot 2022-03-01 at 20 09 22 " src="https://user-images.githubusercontent.com/7399805/156325264-683267c0-4e8f-470c-a8f0-ea7833117cc2.png">

---

**Plugin**: Duolingo Solution Viewer; version 4.10.2;
**System**: macOS 10.15.7 Catalina;
**Browser**: Google Chrome 98.0.4758.109 (Official Build) (x86_64);

**Comment by blmage** [comment]
Thanks for letting me know!
