### ISSUE TITLE
Chrome extension not working with latest Duolingo update

### ISSUE THREAD

**Issue by wizofaus** [blmage/duolingo-solution-viewer#179]
Seems the latest Duolingo update has broken the solution viewer extension?

**Comment by blmage** [comment]
Everything seems fine on my side, could you check if:
- a relevant error is logged in the console? (by [checking the dev tools](https://developer.chrome.com/docs/devtools/open/#console))
- an error occurs in the background script? (by [debugging the extension](https://developer.chrome.com/docs/extensions/mv3/tut_debugging/))
- when an exercise is completed, an element with class `_1tuLI` or `_2Fc1K` is present in the DOM?

Thanks!

**Comment by wizofaus** [comment]
It's working again now, I didn't change anything.

**Comment by wizofaus** [comment]
But not for *all* sentences, and specifically it seems they've added some new ones recently, and it's not working for those.
This was in the console (along with a bunch of 404s):

ui.js:13 Error: Could not find the action link list element.
    at renderChallengeSolutionLink (chrome-extension://idffaipgnlkhfhibgnodeiogpgojcmfm/src/ui.js:51:119025)
    at jb (chrome-extension://idffaipgnlkhfhibgnodeiogpgojcmfm/src/ui.js:51:121067) 'Could not render the solution list link: '

**Comment by blmage** [comment]
Thanks for digging into this! 

Could you point me to a course / lesson where I might encounter such new sentences? (I would not have expected this part of the UI to differ from one exercise to the other, so this is all the more interesting)

**Comment by wizofaus** [comment]
Well this was in the Japanese course, I doubt you'd be able to get to the new sentences without completing quite a few of the previous lessons unfortunately.  I'll see if I can find an earlier lesson with that problem.

**Comment by wizofaus** [comment]
Actually I just started https://www.duolingo.com/skill/ja/Greetings/1, and the first sentence prompt was just おはよう (good morning), and no solutions button was shown for that, but nor were there are any errors in the devtools console.

**Comment by blmage** [comment]
Turns out that the problem was caused by the (new) pronunciation hints, thanks again for your help in fixing this!

**Comment by wizofaus** [comment]
Ah, is there a new version released? Still doesn't seem to be working for me.

**Comment by blmage** [comment]
Yes, the problem should be fixed with version **4.10.4**.
