### ISSUE TITLE
Alternative solutions not shown anymore

### ISSUE THREAD

**Issue by jasnyj** [blmage/duolingo-solution-viewer#190]
Hello,

First of all, thanks for making and maintaining this awesome extension !

Unfortunately, since a few days it is not working for me anymore on the desktop Duolingo website, whether on the new path or old tree. Alternative solutions are not shown anymore: the "SOLUTIONS (number+)" text is not shown on the bottom of the page when a challenge is completed or failed. I also believe typos in listening exercises are not corrected anymore.

I have been migrated to the new path on the desktop website, like most users now I guess, but since I don't like it I'm using the [https://www-internal.duolingo.com/](https://www-internal.duolingo.com/) URL to access the old tree. The extension malfunction may be related to the fact I'm using this alternative URL but I don't think so since the extension has worked correctly with this URL for a few days before it stopped working.

The extension is also not working for me on the new path on [https://www.duolingo.com/](https://www.duolingo.com/), but I personally don't care about that since I don't like the new path and am not using it.

I tried to investigate what's going on but I'm not a web developer... I found that the extension's scripts (observer.js, ui.js and ui.css) seem to be still added correctly to the web page document on www-internal.duolingo.com. For my Finnish course the URL POST-ed to in order to get challenges seems to be https://www-internal.duolingo.com/2017-06-30/sessions, so the URL regexp (/\/[\d]{4}-[\d]{2}-[\d]{2}\/sessions/g) seems still OK to me. Maybe the server's answer format has changed ?

I'm using Firefox 106.0.5 on Linux. I tried to downgrade to 105.0.3 to no avail.

Hope the problem is small enough and you can find a solution when you have time.

**Comment by blmage** [comment]
Thank you very much for letting me know!

Duolingo switched from using `XMLHttpRequest` everywhere to using `fetch`, so the extension was no longer detecting loaded sessions. I didn't notice this earlier unfortunately, because I've been experimenting lately with the pre-fetched sessions A/B test.

In any case, everything should be working fine again with version **4.11.1**.

**Comment by csengh** [comment]
thank's for the fast solution, now all works fine :)

**Comment by jasnyj** [comment]
Confirm it works fine now. Thank you very much !
