### ISSUE TITLE
question for blmage

### ISSUE THREAD

**Issue by brianqsmith** [blmage/duolingo-solution-viewer#192]
@blmage 
I'm new to Github and couldn't figure out to send you a direct message, so I thought I'd post my question here. I hope thats ok. I was wondering if I could hire you to build an online quiz like the Duolingo english test? Not the learning part, just the quiz at [https://englishtest.duolingo.com]. I posted a job on Upwork looking for a developer to build it, and I'm sifting through hundreds of proposals. But you already have exerience working with the platform, so I thought you'd be better suited. Would you be interested?

**Comment by blmage** [comment]
I have just responded to your email. Thanks again for the offer!
