### ISSUE TITLE
Discord link? 

### ISSUE THREAD

**Issue by Danika-Dakika** [blmage/duolingo-solution-viewer#203]
I saw you started a Discord server, but the direct-to-channel link you posted on the Chrome store doesn't get you to the server unless you've already joined it. Do you have an invite link you'd like to replace it with? 

https://discord.com/channels/1171746721324339240/1171746775267295282

![image](https://github.com/blmage/duolingo-solution-viewer/assets/115673540/617095c9-c75d-4087-a359-599a740a1e39)

[Not much of an "issue" I know -- but this was the place for "requests," and it seemed like the quickest way to get word to you!]

**Comment by blmage** [comment]
And here I was wondering why no one had joined yet 😅 Thanks for letting me know, the link is fixed!
