### ISSUE TITLE
Is it not working?

### ISSUE THREAD

**Issue by wjandrea** [blmage/duolingo-solution-viewer#204]
The Solutions button isn't showing up today. Did Duolingo change their layout and break the extension?

I'm doing the French course, if that's relevant. Unit 14. I also tried a lesson in Unit 13.

I relaunched Chrome but no change.

Thanks :)

**Comment by TNG02** [comment]
Same is happening for me across all courses tried so far (Welsh, Chinese & Hawaiian). It was working fine yesterday evening.

I would be sooo gutted if this extension has been stopped by Duolingo changes. I cannot express how useful it has been to me learning Welsh where needing to know the alternative answers is essential to learning my particular dialect of Welsh.

Hopefully it's just a temporary problem but, if not, a really big thank you for writing it and making it available in the fist place.

**Comment by TNG02** [comment]
Thank you - that works perfectly.

I can't say how much I appreciate that quick response!

**Comment by wjandrea** [comment]
@blmage Awesome, thanks for fixing it so quickly! I second TNG02, this extension has been incredibly helpful for me too! :)
