### ISSUE TITLE
Filter text colour looks greyed out

### ISSUE THREAD

**Issue by wjandrea** [blmage/duolingo-solution-viewer#205]
When I write a filter, it looks greyed out:

![screenshot showing the start of a filter](https://github.com/blmage/duolingo-solution-viewer/assets/22385371/a279ee11-0d8d-4a14-84e7-8475288bafe6)

Compare with the placeholder text here:

![screenshot showing a word in the filter box along with the placeholder text](https://github.com/blmage/duolingo-solution-viewer/assets/22385371/42c01f97-017a-4cbf-b34b-62e3ecec623c)

I bet this is related to redesign that spurred #204

Thanks :)

This is low-priority

**Comment by blmage** [comment]
Fixed in version **4.17.3** (I had originally planned to fix this at the same time as implementing Manifest v3 compatibility, hence the delay, but Duo had other ideas it seems!)
