### ISSUE TITLE
conflict with duolingotreeenhancer

### ISSUE THREAD

**Issue by alexseyk** [blmage/duolingo-solution-viewer#26]
Hi, so i use this script https://github.com/camiloaa/duolingotreeenhancer, mainly so  I can listen to the text in base language. Well, the issue is when the script is on your extension does not work :(
Even if i turn all options off in the script, the extension does not work.
Can you look into it? Thanks.

**Comment by blmage** [comment]
Thanks for the report! This is fixed by eceee45c8b0d67580db94d3787c268021c718031 (the userscript modifies the structure of the page, which made some values undetectable for the extension).
