### ISSUE TITLE
Investigate what's going on with Dutch from/to German translations

### ISSUE THREAD

**Issue by blmage** [blmage/duolingo-solution-viewer#4]
Original report here: https://forum.duolingo.com/comment/38731989?comment_id=38964867.

**Comment by blmage** [comment]
May have been fixed by e4380be486c3c730cd393993b5cda363ca2162d0.

**Comment by dlhgl** [comment]
I did a few lessons with the current version of the Duolingo Solution Viewer and the solutions are now shown for Dutch from/to German.

**Comment by blmage** [comment]
Thanks for the feedback! The newest version (`1.2.0`) brings another fix related to this, so we should be all good by now 👍
