### ISSUE TITLE
Make the addon available for Firefox on mobile

### ISSUE THREAD

**Issue by dlhgl** [blmage/duolingo-solution-viewer#5]
When opening the [Firefox addon page](https://addons.mozilla.org/firefox/addon/duolingo-solution-viewer/) on Android a message is shown that the addon is not available on Firefox for Android.

After requesting Desktop Site the addon can be installed and it works well for the mobile version of Duolingo. So maybe it is just a small change to make it available for installation on Firefox on mobile?

**Comment by blmage** [comment]
Good idea, thanks! - it should be available now.
(the layout is not quite optimized yet for mobile though, I'll look into this when I have some time)
