### ISSUE TITLE
Bug: the list of solutions of a challenge remains accessible from the next one using the keyboard shortcuts

### ISSUE THREAD

**Issue by blmage** [blmage/duolingo-solution-viewer#56]
[Original report](https://forum.duolingo.com/comment/38731989?comment_id=40174104).

**Comment by blmage** [comment]
@Atervanda I can't seem to reproduce this, is it working consistently on your side?

**Comment by Atervanda** [comment]
I can't reproduce this anymore either. So, fixed? ¯\\\_(ツ)_/¯

**Comment by blmage** [comment]
Thanks for checking, I guess it is then!
