### ISSUE TITLE
Suggestion: show closest solution in case of a typo

### ISSUE THREAD

**Issue by dlhgl** [blmage/duolingo-solution-viewer#6]
Duolingo doesn't always tell you when you made a typo, e.g. in a "Type what you hear" exercise:

![](https://i.imgur.com/jj4qBym.png)

Showing the closest solution would make it easier to notice a typo.

**Comment by blmage** [comment]
Great idea! I'll try to point out typos like Duolingo does, but we should at least easily be able to display one of the solutions if they all differ significantly from the answer (i.e., regardless of punctuation etc.).
Thanks!

**Comment by blmage** [comment]
This plugin could help to determine the location of typos: https://github.com/kpdecker/jsdiff.

**Comment by blmage** [comment]
Made some progress on this - it probably won't be perfect, but it should still be quite helpful:
![corrected_answer](https://user-images.githubusercontent.com/25432517/83349971-f01ab680-a338-11ea-9be0-499668df54dc.png)

**Comment by dlhgl** [comment]
Looks great!

And will definitely be helpful to learn the correct spelling :)

**Comment by blmage** [comment]
Closed by 57837d6de13b805c629e1f2fe7ca36f7593e1902 (the new version should be available soon on the extension stores). Thanks again for the idea! 👍
