### ISSUE TITLE
Stopped working on Microsoft Edge

### ISSUE THREAD

**Issue by jerrycallahan66** [blmage/duolingo-solution-viewer#99]
I loaded your extension version 3.0.0 on my Microsoft Edge Version 84.0.522.59 (Official build) (64-bit) last week. It worked great and is very helpful. However, today it stopped working, i.e., no prompts or messages.

I tried reloading the extension, restarting the browser, and restarting the PC. While the browser said the extension was there and turned on, nothing showed up on the Duolingo Spanish exercises.

**Comment by jerrycallahan66** [comment]
I just downloaded the same version 3.0.0 on my Google Chrome Version 84.0.4147.125 (Official Build) (64-bit). It does not work here either.

**Comment by ChipBurwell** [comment]
Was working just fine for the last month or so that I've been using it. But it stopped working today. I'm on Firefox 79.0 (64-bit).  Thanks so much for this extension, hope you can get it working again!

**Comment by blmage** [comment]
@jerrycallahan66 @ChipBurwell Thank you very much for the report!

There has been a major UI update on Duolingo -  version [`3.0.1`](https://github.com/blmage/duolingo-solution-viewer/releases/tag/3.0.1) takes it into account, and is now available on both extension stores.

Please let me know if you find anything missing!

**Comment by jerrycallahan66** [comment]
I tried Duolingo on both Google Chrome and Microsoft Edge (chromium based) with your new extension. Neither showed your extended views. 

 

There must be something else wrong.

 

J Callahan

**Comment by jerrycallahan66** [comment]
FYI, I just downloaded FireFox and tried it on Duolingo with your extension. It worked correctly.

 

J Callahan

 

From: jerrycallahan66@gmail.com <jerrycallahan66@gmail.com> 
Sent: August 18, 2020 13:32
To: 'blmage/duolingo-solution-viewer' <reply@reply.github.com>
Subject: RE: [blmage/duolingo-solution-viewer] Stopped working on Microsoft Edge (#99)

 

I tried Duolingo on both Google Chrome and Microsoft Edge (chromium based) with your new extension. Neither showed your extended views. 

 

There must be something else wrong.

 

J Callahan

**Comment by blmage** [comment]
@jerrycallahan66  Can you double check if the extension has been updated to version `3.0.1` on both browsers? Thanks!

**Comment by jerrycallahan66** [comment]
Yes it is the new version on all three browsers. Only FireFox works. 

Cheers,
Jerry

On Aug 19, 2020, at 01:51, blmage <notifications@github.com> wrote:

﻿
@jerrycallahan66 Can you double check if the extension has been updated to version 3.0.1 on both browsers? Thanks!

**Comment by jerrycallahan66** [comment]
All three browsers now work. FireFox worked the first time. Edge worked after I removed the extension and reloaded it. Chrome worked without a reload.

 

What ever you did, has fixed the problem. Thanks.

 

J Callahan
